CC = gcc

CFLAGS = -std=c99
CFLAGS += -Wall -Wextra -Wpedantic
CFLAGS += -O3
CFLAGS += -Ilib/

OBJS = wrapper.o idx_LUT.o exfes.o common.o binomials.o autogenerated_c-tester_deg_2.o autogenerated_c-sequential_deg_2.o

all: sample1 test1 test2

sample1: sample1.o lib/$(OBJS)
	$(CC) -o sample1 sample1.o lib/$(OBJS)

test1: test1.o lib/$(OBJS)
	$(CC) -o test1 test1.o lib/$(OBJS)

test2: test2.o lib/$(OBJS)
	$(CC) -o test2 test2.o lib/$(OBJS)

sample1.o: samples/sample1.c lib/$(OBJS)
	$(CC) $(CFLAGS) -c samples/sample1.c -o sample1.o

test1.o: tests/test1.c lib/$(OBJS)
	$(CC) $(CFLAGS) -c tests/test1.c -o test1.o

test2.o: tests/test2.c lib/$(OBJS)
	$(CC) $(CFLAGS) -c tests/test2.c -o test2.o

%.o: lib/%.c
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean
clean:
	rm -f *.o sample1 test1 test2
