test: autogenerated_asm_deg_2_T_2_el_0.o autogenerated_asm_deg_2_T_3_el_0.o autogenerated_asm_deg_2_T_4_el_0.o autogenerated_c-sequential_deg_2.o autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o autogenerated_c-tester_deg_2.o binomials.o common.o exfes.o idx_LUT.o moebius_transform.o rand.o wrapper.o
	g++ -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 -lstdc++ test.c autogenerated_asm_deg_2_T_2_el_0.o autogenerated_asm_deg_2_T_3_el_0.o autogenerated_asm_deg_2_T_4_el_0.o autogenerated_c-sequential_deg_2.o autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o autogenerated_c-tester_deg_2.o binomials.o common.o exfes.o idx_LUT.o moebius_transform.o rand.o wrapper.o -o test

miner_test: autogenerated_asm_deg_2_T_2_el_0.o autogenerated_asm_deg_2_T_3_el_0.o autogenerated_asm_deg_2_T_4_el_0.o autogenerated_c-sequential_deg_2.o autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o autogenerated_c-tester_deg_2.o binomials.o common.o exfes.o idx_LUT.o moebius_transform.o rand.o wrapper.o
	g++ -Wall -mmmx -msse -msse2 -msse3 -O3 -lstdc++ -Wextra miner_test.c autogenerated_asm_deg_2_T_2_el_0.o autogenerated_asm_deg_2_T_3_el_0.o autogenerated_asm_deg_2_T_4_el_0.o autogenerated_c-sequential_deg_2.o autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o autogenerated_c-tester_deg_2.o binomials.o common.o exfes.o idx_LUT.o moebius_transform.o rand.o wrapper.o -o miner_test

test_wrapper: autogenerated_asm_deg_2_T_2_el_0.o autogenerated_asm_deg_2_T_3_el_0.o autogenerated_asm_deg_2_T_4_el_0.o autogenerated_c-sequential_deg_2.o autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o autogenerated_c-tester_deg_2.o binomials.o common.o idx_LUT.o moebius_transform.o rand.o test_wrapper.o wrapper.o
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 test_wrapper.c autogenerated_asm_deg_2_T_2_el_0.o autogenerated_asm_deg_2_T_3_el_0.o autogenerated_asm_deg_2_T_4_el_0.o autogenerated_c-sequential_deg_2.o autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o autogenerated_c-tester_deg_2.o binomials.o common.o idx_LUT.o moebius_transform.o rand.o wrapper.o -o test_wrapper

autogenerated_asm_deg_2_T_2_el_0.o:
	as autogenerated_asm_deg_2_T_2_el_0.s -o autogenerated_asm_deg_2_T_2_el_0.o

autogenerated_asm_deg_2_T_3_el_0.o:
	as autogenerated_asm_deg_2_T_3_el_0.s -o autogenerated_asm_deg_2_T_3_el_0.o

autogenerated_asm_deg_2_T_4_el_0.o:
	as autogenerated_asm_deg_2_T_4_el_0.s -o autogenerated_asm_deg_2_T_4_el_0.o

autogenerated_c-sequential_deg_2.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 autogenerated_c-sequential_deg_2.c -o autogenerated_c-sequential_deg_2.o -c

autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 autogenerated_c-simd-with-asm_deg_2_T_2_el_0.c -o autogenerated_c-simd-with-asm_deg_2_T_2_el_0.o -c

autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 autogenerated_c-simd-with-asm_deg_2_T_3_el_0.c -o autogenerated_c-simd-with-asm_deg_2_T_3_el_0.o -c

autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 autogenerated_c-simd-with-asm_deg_2_T_4_el_0.c -o autogenerated_c-simd-with-asm_deg_2_T_4_el_0.o -c

autogenerated_c-tester_deg_2.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 autogenerated_c-tester_deg_2.c -o autogenerated_c-tester_deg_2.o -c

exfes.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 exfes.c -o exfes.o -c

binomials.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 binomials.c -o binomials.o -c

common.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 common.c -o common.o -c

idx_LUT.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 idx_LUT.c -o idx_LUT.o -c

moebius_transform.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 moebius_transform.c -o moebius_transform.o -c

rand.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 rand.c -o rand.o -c

wrapper.o:
	gcc -Wall -Wextra -mmmx -msse -msse2 -msse3 -O3 wrapper.c -o wrapper.o -c

clean:
	rm -f test miner_test test_wrapper
	rm -f *.o
