#!/bin/bash

set -e

cd "$( dirname "${BASH_SOURCE[0]}" )"

cp lib/exfes.h exfes.h

{

    cat lib/binomials.h
    cat lib/exfes.h
    cat lib/my_memory.h

    cat lib/exfes_internal.h
    cat lib/idx_LUT.h

    cat lib/fes_interface.h
    cat lib/fes.h

    cat lib/autogenerated_c-sequential_deg_2.c
    cat lib/autogenerated_c-tester_deg_2.c
    cat lib/binomials.c
    cat lib/common.c
    cat lib/exfes.c
    cat lib/idx_LUT.c
    cat lib/my_memory.c
    cat lib/wrapper.c

} | grep -v '#include.*"' > exfes.c
