#include <stdint.h>
#include "fes.h"

void exhaustive_ia32_deg_2(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_2.c
pck_vector_t packed_eval_deg_2(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_2.c
void exhaustive_ia32_deg_3(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_3.c
pck_vector_t packed_eval_deg_3(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_3.c
void exhaustive_ia32_deg_4(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_4.c
pck_vector_t packed_eval_deg_4(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_4.c
void exhaustive_ia32_deg_5(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_5.c
pck_vector_t packed_eval_deg_5(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_5.c
void exhaustive_ia32_deg_6(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_6.c
pck_vector_t packed_eval_deg_6(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_6.c
void exhaustive_ia32_deg_7(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_7.c
pck_vector_t packed_eval_deg_7(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_7.c
void exhaustive_ia32_deg_8(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_8.c
pck_vector_t packed_eval_deg_8(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_8.c
void exhaustive_ia32_deg_9(LUT_t LUT, int n, pck_vector_t F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_sequential_deg_9.c
pck_vector_t packed_eval_deg_9(LUT_t LUT, int n, pck_vector_t F[], uint64_t i); // autogenerated_tester_deg_9.c

#ifdef HAVE_SSE2
void exhaustive_sse2_deg_2_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_2_T_2_el_0.c
void exhaustive_sse2_deg_2_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_2_T_3_el_0.c
void exhaustive_sse2_deg_2_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_2_T_4_el_0.c
void exhaustive_sse2_deg_3_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_3_T_2_el_0.c
void exhaustive_sse2_deg_3_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_3_T_3_el_0.c
void exhaustive_sse2_deg_3_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_3_T_4_el_0.c
void exhaustive_sse2_deg_4_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_4_T_2_el_0.c
void exhaustive_sse2_deg_4_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_4_T_3_el_0.c
void exhaustive_sse2_deg_4_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_4_T_4_el_0.c
void exhaustive_sse2_deg_5_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_5_T_2_el_0.c
void exhaustive_sse2_deg_5_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_5_T_3_el_0.c
void exhaustive_sse2_deg_5_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_5_T_4_el_0.c
void exhaustive_sse2_deg_6_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_6_T_2_el_0.c
void exhaustive_sse2_deg_6_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_6_T_3_el_0.c
void exhaustive_sse2_deg_6_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_6_T_4_el_0.c
void exhaustive_sse2_deg_7_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_7_T_2_el_0.c
void exhaustive_sse2_deg_7_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_7_T_3_el_0.c
void exhaustive_sse2_deg_7_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_7_T_4_el_0.c
void exhaustive_sse2_deg_8_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_8_T_2_el_0.c
void exhaustive_sse2_deg_8_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_8_T_3_el_0.c
void exhaustive_sse2_deg_8_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_8_T_4_el_0.c
void exhaustive_sse2_deg_9_T_2_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_9_T_2_el_0.c
void exhaustive_sse2_deg_9_T_3_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_9_T_3_el_0.c
void exhaustive_sse2_deg_9_T_4_el_0(LUT_t LUT, int n, pck_vector_t nonsimd_F[], solution_callback_t callback, void* callback_state, int verbose); // autogenerated_simd_deg_9_T_4_el_0.c
#ifdef HAVE_64_BITS
extern void func_deg_2_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_2_T_2_el_0.s
extern void func_deg_2_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_2_T_3_el_0.s
extern void func_deg_2_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_2_T_4_el_0.s
extern void func_deg_3_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_3_T_2_el_0.s
extern void func_deg_3_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_3_T_3_el_0.s
extern void func_deg_3_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_3_T_4_el_0.s
extern void func_deg_4_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_4_T_2_el_0.s
extern void func_deg_4_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_4_T_3_el_0.s
extern void func_deg_4_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_4_T_4_el_0.s
extern void func_deg_5_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_5_T_2_el_0.s
extern void func_deg_5_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_5_T_3_el_0.s
extern void func_deg_5_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_5_T_4_el_0.s
extern void func_deg_6_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_6_T_2_el_0.s
extern void func_deg_6_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_6_T_3_el_0.s
extern void func_deg_6_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_6_T_4_el_0.s
extern void func_deg_7_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_7_T_2_el_0.s
extern void func_deg_7_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_7_T_3_el_0.s
extern void func_deg_7_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_7_T_4_el_0.s
extern void func_deg_8_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_8_T_2_el_0.s
extern void func_deg_8_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_8_T_3_el_0.s
extern void func_deg_8_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_8_T_4_el_0.s
extern void func_deg_9_T_2_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_9_T_2_el_0.s
extern void func_deg_9_T_3_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_9_T_3_el_0.s
extern void func_deg_9_T_4_el_0(__m128i *F, uint64_t *F_sp, void *buf, uint64_t *num, uint64_t idx); // autogenerated_asm_deg_9_T_4_el_0.s
#endif
#endif

